version: "2"
plugins:
  eslint:
    enabled: true
    config:
      config: ./.eslintrc.json
checks:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
exclude_paths:
- test/
