version: "2"
plugins:
  eslint:
    enabled: true
    config:
      config: ./.eslintrc
checks:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
exclude_patterns:
- test/
